#! /bin/bash
# FS QA Test No. 001
#
# Test cmtime update after writes to shared writable mmaps
#
#-----------------------------------------------------------------------
# Copyright (c) 2013 Andrew Lutomirski.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    rm -f "$TEST_DIR/file"
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# Modify as appropriate.
_supported_fs generic
_supported_os Linux

"$here/src/mmap_cmtime" "$TEST_DIR/file" 2>&1 | tee "$seqres.full" |grep -v '^  \[DEBUG\]'
status=${PIPESTATUS[0]}

exit $status
